import React from 'react';
export const complianceDetails = () => <div>compliance distinct details for Compliance NIST/CIS/PCI - controls gap analysis</div>;
export const compliance_detail_0 = (p:any)=> <div>compliance 0 NIST 800-53</div>;
export const compliance_detail_1 = (p:any)=> <div>compliance 1 CIS 60</div>;
export const compliance_detail_2 = (p:any)=> <div>compliance 2 PCI 40</div>;
export const compliance_detail_3 = (p:any)=> <div>compliance 3 NIST 800-53</div>;
export const compliance_detail_4 = (p:any)=> <div>compliance 4 CIS 60</div>;
export const compliance_detail_5 = (p:any)=> <div>compliance 5 PCI 40</div>;
export const compliance_detail_6 = (p:any)=> <div>compliance 6 NIST 800-53</div>;
export const compliance_detail_7 = (p:any)=> <div>compliance 7 CIS 60</div>;
export const compliance_detail_8 = (p:any)=> <div>compliance 8 PCI 40</div>;
export const compliance_detail_9 = (p:any)=> <div>compliance 9 NIST 800-53</div>;
export const compliance_detail_10 = (p:any)=> <div>compliance 10 CIS 60</div>;
export const compliance_detail_11 = (p:any)=> <div>compliance 11 PCI 40</div>;
export const compliance_detail_12 = (p:any)=> <div>compliance 12 NIST 800-53</div>;
export const compliance_detail_13 = (p:any)=> <div>compliance 13 CIS 60</div>;
export const compliance_detail_14 = (p:any)=> <div>compliance 14 PCI 40</div>;
export const compliance_detail_15 = (p:any)=> <div>compliance 15 NIST 800-53</div>;
export const compliance_detail_16 = (p:any)=> <div>compliance 16 CIS 60</div>;
export const compliance_detail_17 = (p:any)=> <div>compliance 17 PCI 40</div>;
export const compliance_detail_18 = (p:any)=> <div>compliance 18 NIST 800-53</div>;
export const compliance_detail_19 = (p:any)=> <div>compliance 19 CIS 60</div>;