import React from 'react';
export const uebaDetails = () => <div>ueba distinct details for UEBA baseline deviation, risk scoring</div>;
export const ueba_detail_0 = (p:any)=> <div>ueba 0 30d rolling</div>;
export const ueba_detail_1 = (p:any)=> <div>ueba 1 z-score >3 anomaly</div>;
export const ueba_detail_2 = (p:any)=> <div>ueba 2 entity risk</div>;
export const ueba_detail_3 = (p:any)=> <div>ueba 3 30d rolling</div>;
export const ueba_detail_4 = (p:any)=> <div>ueba 4 z-score >3 anomaly</div>;
export const ueba_detail_5 = (p:any)=> <div>ueba 5 entity risk</div>;
export const ueba_detail_6 = (p:any)=> <div>ueba 6 30d rolling</div>;
export const ueba_detail_7 = (p:any)=> <div>ueba 7 z-score >3 anomaly</div>;
export const ueba_detail_8 = (p:any)=> <div>ueba 8 entity risk</div>;
export const ueba_detail_9 = (p:any)=> <div>ueba 9 30d rolling</div>;
export const ueba_detail_10 = (p:any)=> <div>ueba 10 z-score >3 anomaly</div>;
export const ueba_detail_11 = (p:any)=> <div>ueba 11 entity risk</div>;
export const ueba_detail_12 = (p:any)=> <div>ueba 12 30d rolling</div>;
export const ueba_detail_13 = (p:any)=> <div>ueba 13 z-score >3 anomaly</div>;
export const ueba_detail_14 = (p:any)=> <div>ueba 14 entity risk</div>;
export const ueba_detail_15 = (p:any)=> <div>ueba 15 30d rolling</div>;
export const ueba_detail_16 = (p:any)=> <div>ueba 16 z-score >3 anomaly</div>;
export const ueba_detail_17 = (p:any)=> <div>ueba 17 entity risk</div>;
export const ueba_detail_18 = (p:any)=> <div>ueba 18 30d rolling</div>;
export const ueba_detail_19 = (p:any)=> <div>ueba 19 z-score >3 anomaly</div>;