import React from 'react';
export const threat_intelDetails = () => <div>threat_intel distinct details for Threat intel STIX/TAXII - IOC validation, expiry, bundle</div>;
export const threat_intel_detail_0 = (p:any)=> <div>threat_intel 0 ipv4</div>;
export const threat_intel_detail_1 = (p:any)=> <div>threat_intel 1 domain</div>;
export const threat_intel_detail_2 = (p:any)=> <div>threat_intel 2 hash</div>;
export const threat_intel_detail_3 = (p:any)=> <div>threat_intel 3 url</div>;
export const threat_intel_detail_4 = (p:any)=> <div>threat_intel 4 tlp</div>;
export const threat_intel_detail_5 = (p:any)=> <div>threat_intel 5 ipv4</div>;
export const threat_intel_detail_6 = (p:any)=> <div>threat_intel 6 domain</div>;
export const threat_intel_detail_7 = (p:any)=> <div>threat_intel 7 hash</div>;
export const threat_intel_detail_8 = (p:any)=> <div>threat_intel 8 url</div>;
export const threat_intel_detail_9 = (p:any)=> <div>threat_intel 9 tlp</div>;
export const threat_intel_detail_10 = (p:any)=> <div>threat_intel 10 ipv4</div>;
export const threat_intel_detail_11 = (p:any)=> <div>threat_intel 11 domain</div>;
export const threat_intel_detail_12 = (p:any)=> <div>threat_intel 12 hash</div>;
export const threat_intel_detail_13 = (p:any)=> <div>threat_intel 13 url</div>;
export const threat_intel_detail_14 = (p:any)=> <div>threat_intel 14 tlp</div>;
export const threat_intel_detail_15 = (p:any)=> <div>threat_intel 15 ipv4</div>;
export const threat_intel_detail_16 = (p:any)=> <div>threat_intel 16 domain</div>;
export const threat_intel_detail_17 = (p:any)=> <div>threat_intel 17 hash</div>;
export const threat_intel_detail_18 = (p:any)=> <div>threat_intel 18 url</div>;
export const threat_intel_detail_19 = (p:any)=> <div>threat_intel 19 tlp</div>;