import React from 'react';
export const siemDetails = () => <div>siem distinct details for SIEM detection and correlation - MITRE ATT&CK, rule engine, dedup</div>;
export const siem_detail_0 = (p:any)=> <div>siem 0 T1071</div>;
export const siem_detail_1 = (p:any)=> <div>siem 1 T1059</div>;
export const siem_detail_2 = (p:any)=> <div>siem 2 T1078</div>;
export const siem_detail_3 = (p:any)=> <div>siem 3 T1548</div>;
export const siem_detail_4 = (p:any)=> <div>siem 4 T1071</div>;
export const siem_detail_5 = (p:any)=> <div>siem 5 T1059</div>;
export const siem_detail_6 = (p:any)=> <div>siem 6 T1078</div>;
export const siem_detail_7 = (p:any)=> <div>siem 7 T1548</div>;
export const siem_detail_8 = (p:any)=> <div>siem 8 T1071</div>;
export const siem_detail_9 = (p:any)=> <div>siem 9 T1059</div>;
export const siem_detail_10 = (p:any)=> <div>siem 10 T1078</div>;
export const siem_detail_11 = (p:any)=> <div>siem 11 T1548</div>;
export const siem_detail_12 = (p:any)=> <div>siem 12 T1071</div>;
export const siem_detail_13 = (p:any)=> <div>siem 13 T1059</div>;
export const siem_detail_14 = (p:any)=> <div>siem 14 T1078</div>;
export const siem_detail_15 = (p:any)=> <div>siem 15 T1548</div>;
export const siem_detail_16 = (p:any)=> <div>siem 16 T1071</div>;
export const siem_detail_17 = (p:any)=> <div>siem 17 T1059</div>;
export const siem_detail_18 = (p:any)=> <div>siem 18 T1078</div>;
export const siem_detail_19 = (p:any)=> <div>siem 19 T1548</div>;