import React from 'react';
export const vulnerabilitiesDetails = () => <div>vulnerabilities distinct details for CVE CVSS scoring - NVD, threat 0-100, CPE exposure</div>;
export const vulnerabilities_detail_0 = (p:any)=> <div>vulnerabilities 0 CVSS 9.0 auto playbook</div>;
export const vulnerabilities_detail_1 = (p:any)=> <div>vulnerabilities 1 CPE matching</div>;
export const vulnerabilities_detail_2 = (p:any)=> <div>vulnerabilities 2 NVD feed</div>;
export const vulnerabilities_detail_3 = (p:any)=> <div>vulnerabilities 3 CVSS 9.0 auto playbook</div>;
export const vulnerabilities_detail_4 = (p:any)=> <div>vulnerabilities 4 CPE matching</div>;
export const vulnerabilities_detail_5 = (p:any)=> <div>vulnerabilities 5 NVD feed</div>;
export const vulnerabilities_detail_6 = (p:any)=> <div>vulnerabilities 6 CVSS 9.0 auto playbook</div>;
export const vulnerabilities_detail_7 = (p:any)=> <div>vulnerabilities 7 CPE matching</div>;
export const vulnerabilities_detail_8 = (p:any)=> <div>vulnerabilities 8 NVD feed</div>;
export const vulnerabilities_detail_9 = (p:any)=> <div>vulnerabilities 9 CVSS 9.0 auto playbook</div>;
export const vulnerabilities_detail_10 = (p:any)=> <div>vulnerabilities 10 CPE matching</div>;
export const vulnerabilities_detail_11 = (p:any)=> <div>vulnerabilities 11 NVD feed</div>;
export const vulnerabilities_detail_12 = (p:any)=> <div>vulnerabilities 12 CVSS 9.0 auto playbook</div>;
export const vulnerabilities_detail_13 = (p:any)=> <div>vulnerabilities 13 CPE matching</div>;
export const vulnerabilities_detail_14 = (p:any)=> <div>vulnerabilities 14 NVD feed</div>;
export const vulnerabilities_detail_15 = (p:any)=> <div>vulnerabilities 15 CVSS 9.0 auto playbook</div>;
export const vulnerabilities_detail_16 = (p:any)=> <div>vulnerabilities 16 CPE matching</div>;
export const vulnerabilities_detail_17 = (p:any)=> <div>vulnerabilities 17 NVD feed</div>;
export const vulnerabilities_detail_18 = (p:any)=> <div>vulnerabilities 18 CVSS 9.0 auto playbook</div>;
export const vulnerabilities_detail_19 = (p:any)=> <div>vulnerabilities 19 CPE matching</div>;