import React from 'react';
export const assetsDetails = () => <div>assets distinct details for Asset inventory CMDB - criticality, exposure, EDR staleness</div>;
export const assets_detail_0 = (p:any)=> <div>assets 0 tier0 DC</div>;
export const assets_detail_1 = (p:any)=> <div>assets 1 public IP exposure</div>;
export const assets_detail_2 = (p:any)=> <div>assets 2 EDR 7d</div>;
export const assets_detail_3 = (p:any)=> <div>assets 3 tier0 DC</div>;
export const assets_detail_4 = (p:any)=> <div>assets 4 public IP exposure</div>;
export const assets_detail_5 = (p:any)=> <div>assets 5 EDR 7d</div>;
export const assets_detail_6 = (p:any)=> <div>assets 6 tier0 DC</div>;
export const assets_detail_7 = (p:any)=> <div>assets 7 public IP exposure</div>;
export const assets_detail_8 = (p:any)=> <div>assets 8 EDR 7d</div>;
export const assets_detail_9 = (p:any)=> <div>assets 9 tier0 DC</div>;
export const assets_detail_10 = (p:any)=> <div>assets 10 public IP exposure</div>;
export const assets_detail_11 = (p:any)=> <div>assets 11 EDR 7d</div>;
export const assets_detail_12 = (p:any)=> <div>assets 12 tier0 DC</div>;
export const assets_detail_13 = (p:any)=> <div>assets 13 public IP exposure</div>;
export const assets_detail_14 = (p:any)=> <div>assets 14 EDR 7d</div>;
export const assets_detail_15 = (p:any)=> <div>assets 15 tier0 DC</div>;
export const assets_detail_16 = (p:any)=> <div>assets 16 public IP exposure</div>;
export const assets_detail_17 = (p:any)=> <div>assets 17 EDR 7d</div>;
export const assets_detail_18 = (p:any)=> <div>assets 18 tier0 DC</div>;
export const assets_detail_19 = (p:any)=> <div>assets 19 public IP exposure</div>;