import React from 'react';
export const casesDetails = () => <div>cases distinct details for Case investigation workflow - linking, assignment, review</div>;
export const cases_detail_0 = (p:any)=> <div>cases 0 link case-incident-evidence</div>;
export const cases_detail_1 = (p:any)=> <div>cases 1 least load</div>;
export const cases_detail_2 = (p:any)=> <div>cases 2 peer review</div>;
export const cases_detail_3 = (p:any)=> <div>cases 3 link case-incident-evidence</div>;
export const cases_detail_4 = (p:any)=> <div>cases 4 least load</div>;
export const cases_detail_5 = (p:any)=> <div>cases 5 peer review</div>;
export const cases_detail_6 = (p:any)=> <div>cases 6 link case-incident-evidence</div>;
export const cases_detail_7 = (p:any)=> <div>cases 7 least load</div>;
export const cases_detail_8 = (p:any)=> <div>cases 8 peer review</div>;
export const cases_detail_9 = (p:any)=> <div>cases 9 link case-incident-evidence</div>;
export const cases_detail_10 = (p:any)=> <div>cases 10 least load</div>;
export const cases_detail_11 = (p:any)=> <div>cases 11 peer review</div>;
export const cases_detail_12 = (p:any)=> <div>cases 12 link case-incident-evidence</div>;
export const cases_detail_13 = (p:any)=> <div>cases 13 least load</div>;
export const cases_detail_14 = (p:any)=> <div>cases 14 peer review</div>;
export const cases_detail_15 = (p:any)=> <div>cases 15 link case-incident-evidence</div>;
export const cases_detail_16 = (p:any)=> <div>cases 16 least load</div>;
export const cases_detail_17 = (p:any)=> <div>cases 17 peer review</div>;
export const cases_detail_18 = (p:any)=> <div>cases 18 link case-incident-evidence</div>;
export const cases_detail_19 = (p:any)=> <div>cases 19 least load</div>;