import React from 'react';
export const incidentsDetails = () => <div>incidents distinct details for Incident lifecycle - SLA, timeline, escalation, assignment</div>;
export const incidents_detail_0 = (p:any)=> <div>incidents 0 SLA 4h critical</div>;
export const incidents_detail_1 = (p:any)=> <div>incidents 1 timeline immutable</div>;
export const incidents_detail_2 = (p:any)=> <div>incidents 2 escalate if failed>3</div>;
export const incidents_detail_3 = (p:any)=> <div>incidents 3 SLA 4h critical</div>;
export const incidents_detail_4 = (p:any)=> <div>incidents 4 timeline immutable</div>;
export const incidents_detail_5 = (p:any)=> <div>incidents 5 escalate if failed>3</div>;
export const incidents_detail_6 = (p:any)=> <div>incidents 6 SLA 4h critical</div>;
export const incidents_detail_7 = (p:any)=> <div>incidents 7 timeline immutable</div>;
export const incidents_detail_8 = (p:any)=> <div>incidents 8 escalate if failed>3</div>;
export const incidents_detail_9 = (p:any)=> <div>incidents 9 SLA 4h critical</div>;
export const incidents_detail_10 = (p:any)=> <div>incidents 10 timeline immutable</div>;
export const incidents_detail_11 = (p:any)=> <div>incidents 11 escalate if failed>3</div>;
export const incidents_detail_12 = (p:any)=> <div>incidents 12 SLA 4h critical</div>;
export const incidents_detail_13 = (p:any)=> <div>incidents 13 timeline immutable</div>;
export const incidents_detail_14 = (p:any)=> <div>incidents 14 escalate if failed>3</div>;
export const incidents_detail_15 = (p:any)=> <div>incidents 15 SLA 4h critical</div>;
export const incidents_detail_16 = (p:any)=> <div>incidents 16 timeline immutable</div>;
export const incidents_detail_17 = (p:any)=> <div>incidents 17 escalate if failed>3</div>;
export const incidents_detail_18 = (p:any)=> <div>incidents 18 SLA 4h critical</div>;
export const incidents_detail_19 = (p:any)=> <div>incidents 19 timeline immutable</div>;