import React from 'react';
export const log_ingestDetails = () => <div>log_ingest distinct details for Log ingestion pipeline - CEF, syslog, JSON, EPS 10k</div>;
export const log_ingest_detail_0 = (p:any)=> <div>log_ingest 0 CEF header</div>;
export const log_ingest_detail_1 = (p:any)=> <div>log_ingest 1 syslog rfc5424</div>;
export const log_ingest_detail_2 = (p:any)=> <div>log_ingest 2 JSON nested</div>;
export const log_ingest_detail_3 = (p:any)=> <div>log_ingest 3 CEF header</div>;
export const log_ingest_detail_4 = (p:any)=> <div>log_ingest 4 syslog rfc5424</div>;
export const log_ingest_detail_5 = (p:any)=> <div>log_ingest 5 JSON nested</div>;
export const log_ingest_detail_6 = (p:any)=> <div>log_ingest 6 CEF header</div>;
export const log_ingest_detail_7 = (p:any)=> <div>log_ingest 7 syslog rfc5424</div>;
export const log_ingest_detail_8 = (p:any)=> <div>log_ingest 8 JSON nested</div>;
export const log_ingest_detail_9 = (p:any)=> <div>log_ingest 9 CEF header</div>;
export const log_ingest_detail_10 = (p:any)=> <div>log_ingest 10 syslog rfc5424</div>;
export const log_ingest_detail_11 = (p:any)=> <div>log_ingest 11 JSON nested</div>;
export const log_ingest_detail_12 = (p:any)=> <div>log_ingest 12 CEF header</div>;
export const log_ingest_detail_13 = (p:any)=> <div>log_ingest 13 syslog rfc5424</div>;
export const log_ingest_detail_14 = (p:any)=> <div>log_ingest 14 JSON nested</div>;
export const log_ingest_detail_15 = (p:any)=> <div>log_ingest 15 CEF header</div>;
export const log_ingest_detail_16 = (p:any)=> <div>log_ingest 16 syslog rfc5424</div>;
export const log_ingest_detail_17 = (p:any)=> <div>log_ingest 17 JSON nested</div>;
export const log_ingest_detail_18 = (p:any)=> <div>log_ingest 18 CEF header</div>;
export const log_ingest_detail_19 = (p:any)=> <div>log_ingest 19 syslog rfc5424</div>;