import React from 'react';
export const huntingDetails = () => <div>hunting distinct details for Threat hunting hypotheses - KQL, execution</div>;
export const hunting_detail_0 = (p:any)=> <div>hunting 0 hypothesis APT29</div>;
export const hunting_detail_1 = (p:any)=> <div>hunting 1 KQL translate</div>;
export const hunting_detail_2 = (p:any)=> <div>hunting 2 hits confidence</div>;
export const hunting_detail_3 = (p:any)=> <div>hunting 3 hypothesis APT29</div>;
export const hunting_detail_4 = (p:any)=> <div>hunting 4 KQL translate</div>;
export const hunting_detail_5 = (p:any)=> <div>hunting 5 hits confidence</div>;
export const hunting_detail_6 = (p:any)=> <div>hunting 6 hypothesis APT29</div>;
export const hunting_detail_7 = (p:any)=> <div>hunting 7 KQL translate</div>;
export const hunting_detail_8 = (p:any)=> <div>hunting 8 hits confidence</div>;
export const hunting_detail_9 = (p:any)=> <div>hunting 9 hypothesis APT29</div>;
export const hunting_detail_10 = (p:any)=> <div>hunting 10 KQL translate</div>;
export const hunting_detail_11 = (p:any)=> <div>hunting 11 hits confidence</div>;
export const hunting_detail_12 = (p:any)=> <div>hunting 12 hypothesis APT29</div>;
export const hunting_detail_13 = (p:any)=> <div>hunting 13 KQL translate</div>;
export const hunting_detail_14 = (p:any)=> <div>hunting 14 hits confidence</div>;
export const hunting_detail_15 = (p:any)=> <div>hunting 15 hypothesis APT29</div>;
export const hunting_detail_16 = (p:any)=> <div>hunting 16 KQL translate</div>;
export const hunting_detail_17 = (p:any)=> <div>hunting 17 hits confidence</div>;
export const hunting_detail_18 = (p:any)=> <div>hunting 18 hypothesis APT29</div>;
export const hunting_detail_19 = (p:any)=> <div>hunting 19 KQL translate</div>;