import React from 'react';
export const playbooksDetails = () => <div>playbooks distinct details for SOAR playbooks - enrich, contain, ticket, dry-run</div>;
export const playbooks_detail_0 = (p:any)=> <div>playbooks 0 enrich</div>;
export const playbooks_detail_1 = (p:any)=> <div>playbooks 1 contain host</div>;
export const playbooks_detail_2 = (p:any)=> <div>playbooks 2 block IP</div>;
export const playbooks_detail_3 = (p:any)=> <div>playbooks 3 create ticket</div>;
export const playbooks_detail_4 = (p:any)=> <div>playbooks 4 enrich</div>;
export const playbooks_detail_5 = (p:any)=> <div>playbooks 5 contain host</div>;
export const playbooks_detail_6 = (p:any)=> <div>playbooks 6 block IP</div>;
export const playbooks_detail_7 = (p:any)=> <div>playbooks 7 create ticket</div>;
export const playbooks_detail_8 = (p:any)=> <div>playbooks 8 enrich</div>;
export const playbooks_detail_9 = (p:any)=> <div>playbooks 9 contain host</div>;
export const playbooks_detail_10 = (p:any)=> <div>playbooks 10 block IP</div>;
export const playbooks_detail_11 = (p:any)=> <div>playbooks 11 create ticket</div>;
export const playbooks_detail_12 = (p:any)=> <div>playbooks 12 enrich</div>;
export const playbooks_detail_13 = (p:any)=> <div>playbooks 13 contain host</div>;
export const playbooks_detail_14 = (p:any)=> <div>playbooks 14 block IP</div>;
export const playbooks_detail_15 = (p:any)=> <div>playbooks 15 create ticket</div>;
export const playbooks_detail_16 = (p:any)=> <div>playbooks 16 enrich</div>;
export const playbooks_detail_17 = (p:any)=> <div>playbooks 17 contain host</div>;
export const playbooks_detail_18 = (p:any)=> <div>playbooks 18 block IP</div>;
export const playbooks_detail_19 = (p:any)=> <div>playbooks 19 create ticket</div>;