import React from 'react';
export const forensicsDetails = () => <div>forensics distinct details for Forensic evidence hashing, chain-of-custody, timeline</div>;
export const forensics_detail_0 = (p:any)=> <div>forensics 0 sha256 chain</div>;
export const forensics_detail_1 = (p:any)=> <div>forensics 1 custody who/when</div>;
export const forensics_detail_2 = (p:any)=> <div>forensics 2 clock skew 5min</div>;
export const forensics_detail_3 = (p:any)=> <div>forensics 3 sha256 chain</div>;
export const forensics_detail_4 = (p:any)=> <div>forensics 4 custody who/when</div>;
export const forensics_detail_5 = (p:any)=> <div>forensics 5 clock skew 5min</div>;
export const forensics_detail_6 = (p:any)=> <div>forensics 6 sha256 chain</div>;
export const forensics_detail_7 = (p:any)=> <div>forensics 7 custody who/when</div>;
export const forensics_detail_8 = (p:any)=> <div>forensics 8 clock skew 5min</div>;
export const forensics_detail_9 = (p:any)=> <div>forensics 9 sha256 chain</div>;
export const forensics_detail_10 = (p:any)=> <div>forensics 10 custody who/when</div>;
export const forensics_detail_11 = (p:any)=> <div>forensics 11 clock skew 5min</div>;
export const forensics_detail_12 = (p:any)=> <div>forensics 12 sha256 chain</div>;
export const forensics_detail_13 = (p:any)=> <div>forensics 13 custody who/when</div>;
export const forensics_detail_14 = (p:any)=> <div>forensics 14 clock skew 5min</div>;
export const forensics_detail_15 = (p:any)=> <div>forensics 15 sha256 chain</div>;
export const forensics_detail_16 = (p:any)=> <div>forensics 16 custody who/when</div>;
export const forensics_detail_17 = (p:any)=> <div>forensics 17 clock skew 5min</div>;
export const forensics_detail_18 = (p:any)=> <div>forensics 18 sha256 chain</div>;
export const forensics_detail_19 = (p:any)=> <div>forensics 19 custody who/when</div>;