import React from 'react';
export const responseDetails = () => <div>response distinct details for Incident response containment, eradication</div>;
export const response_detail_0 = (p:any)=> <div>response 0 isolate host</div>;
export const response_detail_1 = (p:any)=> <div>response 1 kill process</div>;
export const response_detail_2 = (p:any)=> <div>response 2 restore backup</div>;
export const response_detail_3 = (p:any)=> <div>response 3 isolate host</div>;
export const response_detail_4 = (p:any)=> <div>response 4 kill process</div>;
export const response_detail_5 = (p:any)=> <div>response 5 restore backup</div>;
export const response_detail_6 = (p:any)=> <div>response 6 isolate host</div>;
export const response_detail_7 = (p:any)=> <div>response 7 kill process</div>;
export const response_detail_8 = (p:any)=> <div>response 8 restore backup</div>;
export const response_detail_9 = (p:any)=> <div>response 9 isolate host</div>;
export const response_detail_10 = (p:any)=> <div>response 10 kill process</div>;
export const response_detail_11 = (p:any)=> <div>response 11 restore backup</div>;
export const response_detail_12 = (p:any)=> <div>response 12 isolate host</div>;
export const response_detail_13 = (p:any)=> <div>response 13 kill process</div>;
export const response_detail_14 = (p:any)=> <div>response 14 restore backup</div>;
export const response_detail_15 = (p:any)=> <div>response 15 isolate host</div>;
export const response_detail_16 = (p:any)=> <div>response 16 kill process</div>;
export const response_detail_17 = (p:any)=> <div>response 17 restore backup</div>;
export const response_detail_18 = (p:any)=> <div>response 18 isolate host</div>;
export const response_detail_19 = (p:any)=> <div>response 19 kill process</div>;